// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPRFxQoaOliJaryM_cm626uAK2UV_HxwU',
    appId: '1:880585672188:web:e9bac4139385b8ab805e79',
    messagingSenderId: '880585672188',
    projectId: 'chatapp-ca005',
    authDomain: 'chatapp-ca005.firebaseapp.com',
    storageBucket: 'chatapp-ca005.appspot.com',
    measurementId: 'G-H8S0Q5V66V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz5nligOa7znQFSKNNv3bTbX7jaL9FliY',
    appId: '1:880585672188:android:94f2f39afae51fc4805e79',
    messagingSenderId: '880585672188',
    projectId: 'chatapp-ca005',
    storageBucket: 'chatapp-ca005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2HI9p2hRvOi3j9_w06RuzmsZNUz_69X0',
    appId: '1:880585672188:ios:2fd2e71eabd43922805e79',
    messagingSenderId: '880585672188',
    projectId: 'chatapp-ca005',
    storageBucket: 'chatapp-ca005.appspot.com',
    iosClientId: '880585672188-g1ur9mq87ar9bb6ielhhbqj2rro8d472.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2HI9p2hRvOi3j9_w06RuzmsZNUz_69X0',
    appId: '1:880585672188:ios:2fd2e71eabd43922805e79',
    messagingSenderId: '880585672188',
    projectId: 'chatapp-ca005',
    storageBucket: 'chatapp-ca005.appspot.com',
    iosClientId: '880585672188-g1ur9mq87ar9bb6ielhhbqj2rro8d472.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
